#!/usr/bin/env bash
#
# ispwned - determine if a password, or SHA-1 of a password has been Pwned
#
# We determine if passwords, or the SHA-1 of passwords (if -s was used)
# are found in the Pwned password tree.
#
# A good definition of Pwned is found at:
#
#   https://en.wikipedia.org/wiki/Leet#Owned_and_pwned
#
#   Pwned is a slang form of owned: to appropriate or to conquer to gain ownership.
#
# For information as to why a Pwned password should NOT be used, see:
#
#   https://haveibeenpwned.com/Passwords
#   https://haveibeenpwned.com/FAQs
#
# Normally we download the 4 level directory tree of bzip2 compressed password files,
# without DOS junk, and each file ending in a newline, via the command:
#
#        pwned-pw-download -v 5 /path/to/pwned.pw.tree
#
# where "/path/to/pwned.pw.tree" is the topdir.
#
# There is an alternative that we allow: NOT bzip2 compression:
#
#        pwned-pw-download -b -v 5 /path/to/pwned.pw.tree
#
# For information on pwned-pw-download see:
#
#   https://github.com/lcn2/pwned-pw-download
#
# This includes information about the contents of the 4 level directory tree.
#
# NOTE: We do not care about the password count in in the Pwned password tree.
#       Even a 0 count is good enough to declare the password Pwned.
#       A 0 count could be a way that a password is declared Pwned when
#       the number of instances found is unknown.  Moreover counts <= 0
#       could be the result of an integer overflow in the part of the
#       creators of the Pwned password dataset.
#
# Copyright (c) 2025 by Landon Curt Noll.  All Rights Reserved.
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby granted,
# provided that the above copyright, this permission notice and text
# this comment, and the disclaimer below appear in all of the following:
#
#       supporting documentation
#       source copies
#       source works derived from this source
#       binaries derived from this source or from derived source
#
# LANDON CURT NOLL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL LANDON CURT NOLL BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
# USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# chongo (Landon Curt Noll) /\oo/\
#
# http://www.isthe.com/chongo/index.html
# https://github.com/lcn2
#
# Share and enjoy!  :-)


# setup
#
export VERSION="1.0.0 2025-12-04"
NAME=$(basename "$0")
export NAME
#
export V_FLAG=0
export S_FLAG=
export Q_FLAG=
export O_FLAG=
#
export EXIT_CODE="0"
#
export TOPDIR="/usr/local/share/pwned.pw.tree"
#
BZGREP_TOOL=$(type -P bzgrep)
export BZGREP_TOOL
#
GREP_TOOL=$(type -P grep)
export GREP_TOOL
#
SHA1SUM_TOOL=$(type -P sha1sum)
export SHA1SUM_TOOL


# usage
#
export USAGE="usage: $NAME [-h] [-v level] [-V] [-d topdir] [-b bzgrep] [-g grep] [-S sha1sum] [-s] [-q] [-o] [arg ...]

    -h          print help message and exit
    -v level    set verbosity level (def level: $V_FLAG)
    -V          print version string and exit

    -d topdir	Pwned password tree is under topdir (def: $TOPDIR)
    -b bzgrep	path to bzgrep tool (def: $BZGREP_TOOL)
    -g grep	path to grep tool (def: $GREP_TOOL)
    -S sha1sum	path to the sha1sum tool (def: $SHA1SUM_TOOL)

    -s          args are SHA-1 hashes (def: args are passwords)
    -q		stay quiet about Pwned passwords/hashes (def: announce Pwned passwords/hashes on stdout)
    -o		announce non-Pwned passwords/hashes on stdout (def: stay quiet about non-Pwned passwords/hashes)

    [arg ...]	args are passwords, or SHA-1 hashes is -s (def: read from stdin)

Exit codes:
     0         no evidence that a password (or hash if -s) has been Pwned
     1	       at least 1 password (or hash if -s) was found to be Pwned
     2         -h and help string printed or -V and version string printed
     3         command line error
     4	       topdir not found, or is not searchable, or some file under topdir was not found, or is not readable
     5	       grep tool not found, or is not executable
     6	       bzgrep tool not found, or is not executable
     7	       sha1sum tool not found, or is not executable, or sha1sum tool exited non-zero
     8	       line read or arg was empty (0 length), or hash was not a valid SHA-1 hash
 >= 10         internal error

$NAME version: $VERSION"


# parse command line
#
while getopts :hv:Vd:b:g:S:sqo flag; do
  case "$flag" in
    h) echo "$USAGE"
	exit 2
	;;
    v) V_FLAG="$OPTARG"
	;;
    V) echo "$VERSION"
	exit 2
	;;
    d) TOPDIR="$OPTARG"
        ;;
    b) BZGREP_TOOL="$OPTARG"
        ;;
    g) GREP_TOOL="$OPTARG"
        ;;
    S) SHA1SUM_TOOL="$OPTARG"
        ;;
    s) S_FLAG="true"
	;;
    q) Q_FLAG="true"
	;;
    o) O_FLAG="true"
	;;
    \?) echo "$NAME: ERROR: invalid option: -$OPTARG" 1>&2
	echo 1>&2
	echo "$USAGE" 1>&2
	exit 3
	;;
    :) echo "$NAME: ERROR: option -$OPTARG requires an argument" 1>&2
	echo 1>&2
	echo "$USAGE" 1>&2
	exit 3
	;;
    *) echo "$NAME: ERROR: unexpected value from getopts: $flag" 1>&2
	echo 1>&2
	echo "$USAGE" 1>&2
	exit 3
	;;
  esac
done
if [[ $V_FLAG -ge 1 ]]; then
    echo "$NAME: debug[1]: debug level: $V_FLAG" 1>&2
fi
#
# remove the options
#
shift $(( OPTIND - 1 ));


# verify topdir is readable
#
if [[ ! -e $TOPDIR ]]; then
    echo "$NAME: ERROR: topdir is non-existent: $TOPDIR" 1>&2
    exit 4
fi
if [[ ! -d $TOPDIR ]]; then
    echo "$NAME: ERROR: topdir not a directory: $TOPDIR" 1>&2
    exit 4
fi
if [[ ! -x $TOPDIR ]]; then
    echo "$NAME: ERROR: topdir is not a searchable directory: $TOPDIR" 1>&2
    exit 4
fi


# verify that the grep tool is executable
#
if [[ ! -e $GREP_TOOL ]]; then
    echo  "$NAME: ERROR: grep does not exist: $GREP_TOOL" 1>&2
    exit 5
fi
if [[ ! -f $GREP_TOOL ]]; then
    echo  "$NAME: ERROR: grep is not a regular file: $GREP_TOOL" 1>&2
    exit 5
fi
if [[ ! -x $GREP_TOOL ]]; then
    echo  "$NAME: ERROR: grep is not an executable file: $GREP_TOOL" 1>&2
    exit 5
fi


# verify that the bzgrep tool is executable
#
if [[ ! -e $BZGREP_TOOL ]]; then
    echo  "$NAME: ERROR: bzgrep does not exist: $BZGREP_TOOL" 1>&2
    exit 6
fi
if [[ ! -f $BZGREP_TOOL ]]; then
    echo  "$NAME: ERROR: bzgrep is not a regular file: $BZGREP_TOOL" 1>&2
    exit 6
fi
if [[ ! -x $BZGREP_TOOL ]]; then
    echo  "$NAME: ERROR: bzgrep is not an executable file: $BZGREP_TOOL" 1>&2
    exit 6
fi


# verify that the sha1sum tool is executable if -s was NOT given
#
if [[ -z $S_FLAG ]]; then
    if [[ ! -e $SHA1SUM_TOOL ]]; then
	echo  "$NAME: ERROR: sha1sum does not exist: $SHA1SUM_TOOL" 1>&2
	exit 7
    fi
    if [[ ! -f $SHA1SUM_TOOL ]]; then
	echo  "$NAME: ERROR: sha1sum is not a regular file: $SHA1SUM_TOOL" 1>&2
	exit 7
    fi
    if [[ ! -x $SHA1SUM_TOOL ]]; then
	echo  "$NAME: ERROR: sha1sum is not an executable file: $SHA1SUM_TOOL" 1>&2
	exit 7
    fi
fi


# print running info if verbose
#
# If -v 3 or higher, print exported variables in order that they were exported.
#
if [[ $V_FLAG -ge 3 ]]; then
    echo "$NAME: debug[3]: VERSION=$VERSION" 1>&2
    echo "$NAME: debug[3]: NAME=$NAME" 1>&2
    echo "$NAME: debug[3]: V_FLAG=$V_FLAG" 1>&2
    echo "$NAME: debug[3]: S_FLAG=$S_FLAG" 1>&2
    echo "$NAME: debug[3]: Q_FLAG=$Q_FLAG" 1>&2
    echo "$NAME: debug[3]: O_FLAG=$O_FLAG" 1>&2
    echo "$NAME: debug[3]: EXIT_CODE=$EXIT_CODE" 1>&2
    echo "$NAME: debug[3]: TOPDIR=$TOPDIR" 1>&2
    echo "$NAME: debug[3]: GREP_TOOL=$GREP_TOOL" 1>&2
    echo "$NAME: debug[3]: BZGREP_TOOL=$BZGREP_TOOL" 1>&2
    echo "$NAME: debug[3]: SHA1SUM_TOOL=$SHA1SUM_TOOL" 1>&2
fi

# create a temporary exit code
#
# It is a pain to set the EXIT_CODE deep inside a loop, so we write the EXIT_CODE into a file
# and read the file (setting EXIT_CODE again) after the loop.  A hack, but good enough for our needs.
#
TMPDIR=${TMPDIR:-/tmp}
export TMP_EXIT_CODE="$TMPDIR/.tmp.$NAME.EXIT_CODE.$$.tmp"
if [[ $V_FLAG -ge 3 ]]; then
    echo  "$NAME: debug[3]: temporary exit code: $TMP_EXIT_CODE" 1>&2
fi
trap 'rm -f $TMP_EXIT_CODE; exit' 0 1 2 3 15
rm -f "$TMP_EXIT_CODE"
if [[ -e $TMP_EXIT_CODE ]]; then
    echo "$NAME: ERROR: cannot remove temporary exit code: $TMP_EXIT_CODE" 1>&2
    exit 10
fi
echo "$EXIT_CODE" > "$TMP_EXIT_CODE"
if [[ ! -e $TMP_EXIT_CODE ]]; then
    echo "$NAME: ERROR: cannot create temporary exit code: $TMP_EXIT_CODE" 1>&2
    exit 11
fi


# case: no args, read lines from stdin
#
if [[ $# -le 0 ]]; then

    while read -r line; do
	echo "$line"
    done

# case: args are given
else
    for line in "$@"; do
	echo "$line"
    done
fi |

# check each line if it is pwned
#
while read -r line; do


    # line cannot be empty
    #
    if [[ -z $line ]]; then
	if [[ $# -le 0 ]]; then
	    echo "$NAME: ERROR: stdin line is empty (0 length)" 1>&2
	else
	    echo "$NAME: ERROR: arg is empty (0 length)" 1>&2
	fi
	EXIT_CODE=8 # exit 8
	echo "$EXIT_CODE" > "$TMP_EXIT_CODE"
	echo "$NAME: Notice: EXIT_CODE set to: $EXIT_CODE" 1>&2
	continue
    fi

    # case: was not -s was used, convert line into a SHA-1 hash
    #
    if [[ -z $S_FLAG ]]; then

	# SHA-1 hash the password
	#
	# NOTE: We use echo -n, instead of using <<< "$line" because we don't want hash the final newline!
	#
	SHA1_HASH=$(echo -n "$line" | $SHA1SUM_TOOL - 2>/dev/null)
	status="$?"
	if [[ $status -ne 0 ]]; then
	    echo  "$NAME: ERROR: $SHA1SUM_TOOL - of $line failed, error: $status" 1>&2
	    EXIT_CODE=7 # exit 7
	    echo "$EXIT_CODE" > "$TMP_EXIT_CODE"
	    echo "$NAME: Notice: EXIT_CODE set to: $EXIT_CODE" 1>&2
	    continue
	fi

    # case: -s was used, line is a SHA-1 hash
    #
    else
	SHA1_HASH=${line%% *}
    fi

    # SHA-1 hash line cannot be empty
    #
    if [[ -z $SHA1_HASH ]]; then
	echo "$NAME: ERROR: SHA-1 hash line is empty (0 length)" 1>&2
	EXIT_CODE=8 # exit 8
	echo "$EXIT_CODE" > "$TMP_EXIT_CODE"
	echo "$NAME: Notice: EXIT_CODE set to: $EXIT_CODE" 1>&2
	continue
    fi

    # obtain just the first word of SHA-1 hash line: just the SHA-1 hex value
    #
    SHA1_HASH=${SHA1_HASH%% *}

    # convert SHA-1 value into UPPER CASE
    #
    SHA1_HASH=${SHA1_HASH^^}

    # SHA-1 hash cannot be empty
    #
    if [[ -z $SHA1_HASH ]]; then
	echo "$NAME: ERROR: SHA-1 hash is empty (0 length)" 1>&2
	EXIT_CODE=8 # exit 8
	echo "$EXIT_CODE" > "$TMP_EXIT_CODE"
	echo "$NAME: Notice: EXIT_CODE set to: $EXIT_CODE" 1>&2
	continue

    # SHA-1 must be 40 chars long
    #
    elif [[ ${#SHA1_HASH} -ne 40 ]]; then
	echo "$NAME: ERROR: SHA-1 hash: $SHA1_HASH is not 40 chars long: ${#SHA1_HASH}" 1>&2
	EXIT_CODE=8 # exit 8
	echo "$EXIT_CODE" > "$TMP_EXIT_CODE"
	echo "$NAME: Notice: EXIT_CODE set to: $EXIT_CODE" 1>&2
	continue
    fi

    # SHA-1 must be UPPER CASE HEX only
    #
    if ! [[ $SHA1_HASH =~ ^[0-9A-F]+$ ]]; then
	echo "$NAME: ERROR: SHA-1 string: $SHA1_HASH does not match ^[0-9A-F]+\$" 1>&2
	EXIT_CODE=8 # exit 8
	echo "$EXIT_CODE" > "$TMP_EXIT_CODE"
	echo "$NAME: Notice: EXIT_CODE set to: $EXIT_CODE" 1>&2
	continue
    fi
    if [[ $V_FLAG -ge 3 ]]; then
	echo "$NAME: debug[3]: will lookup SHA-1 hash: $SHA1_HASH" 1>&2
    fi

    # build the components we need to lookup under the Pwned password tree
    #
    HASH_I=${SHA1_HASH:0:1}
    HASH_J=${SHA1_HASH:1:1}
    HASH_K=${SHA1_HASH:2:1}
    HASH_IJKLM=${SHA1_HASH:0:5}
    HASH_REGEX="^${SHA1_HASH:5:40}:"

    # determine the Pwned password tree filename
    #
    FILE_PATH="$TOPDIR/$HASH_I/$HASH_J/$HASH_K/$HASH_IJKLM"
    FILE_PATH_BZ2="$FILE_PATH.bz2"
    if [[ $V_FLAG -ge 3 ]]; then
	echo "$NAME: debug[3]: FILE_PATH_BZ2: $FILE_PATH_BZ2" 1>&2
    fi
    if [[ $V_FLAG -ge 5 ]]; then
	echo "$NAME: debug[5]: FILE_PATH: $FILE_PATH" 1>&2
    fi

    # case: we have a bz2 compressed file in the password tree filename
    #
    FOUND=""
    if [[ -f $FILE_PATH_BZ2 && -r $FILE_PATH_BZ2 && -s $FILE_PATH_BZ2 ]]; then

	# Look for a line in a compressed file that starts with the rest of the SHA-1 hash
	#
	if [[ $V_FLAG -ge 5 ]]; then
	    echo "$NAME: debug[5]: about to execute: $BZGREP_TOOL -a -e $HASH_REGEX -h -- $FILE_PATH_BZ2" 1>&2
	fi
	FOUND=$("$BZGREP_TOOL" -a -e "$HASH_REGEX" -h -- "$FILE_PATH_BZ2" 2>/dev/null)

    # case: we have regular file in the password tree filename
    #
    elif [[ -f $FILE_PATH && -r $FILE_PATH && -s $FILE_PATH ]]; then

	# Look for a line that starts with the rest of the SHA-1 hash
	#
	if [[ $V_FLAG -ge 5 ]]; then
	    echo "$NAME: debug[5]: about to execute: $GREP_TOOL -a -e $HASH_REGEX -h -- $FILE_PATH" 1>&2
	fi
	FOUND=$("$GREP_TOOL" -a -e "$HASH_REGEX" -h -- "$FILE_PATH" 2>/dev/null)

    # case: missing password tree filename
    #
    # This should NOT happen if the password tree is complete.
    #
    else
	echo "$NAME: ERROR: PLUS non-empty readable Pwned password tree file not found: $FILE_PATH.bz2" 1>&2
	echo "$NAME: ERROR: non-empty readable Pwned password tree file not found: $FILE_PATH" 1>&2
	EXIT_CODE=4 # exit 4
	echo "$EXIT_CODE" > "$TMP_EXIT_CODE"
	echo "$NAME: Notice: EXIT_CODE set to: $EXIT_CODE" 1>&2
	continue
    fi

    # case: match found, password is Pwned
    #
    if [[ -n $FOUND ]]; then

	# determine count without any trailing whitespace
	#
	# If for some reason the match plus : is no found, then just return was was found in the database.
	#
	COUNT=${FOUND##*:}
	COUNT=${COUNT:-$FOUND}	 # paranoia
	COUNT=${COUNT%%"${COUNT##*[![:space:]]}"}

	# note Pwned password
	#
	if [[ -z $Q_FLAG ]]; then
	    if [[ -z $S_FLAG ]]; then
		echo "$NAME: Notice: password: $line has been Pwned $COUNT times"
	    else
		echo "$NAME: Notice: SHA-1 hash: $SHA1_HASH found with count: $COUNT"
	    fi
	    if [[ $V_FLAG -ge 1 ]]; then
		echo "$NAME: debug[1]: Pwned line: $FOUND" 1>&2
	    fi
	fi
	EXIT_CODE=1 # exit 1
	echo "$EXIT_CODE" > "$TMP_EXIT_CODE"

    # case: no match, no evidence that password has been Pwned
    #
    elif [[ -n $O_FLAG ]]; then
	if [[ -z $S_FLAG ]]; then
	    echo "$NAME: Notice: no evidence found that password: $line has been Pwned"
	else
	    echo "$NAME: Notice: no evidence found that SHA-1 hash: $SHA1_HASH has been Pwned"
	fi
    fi
done


# All Done!!! -- Jessica Noll, Age 2
#
if [[ -s $TMP_EXIT_CODE ]]; then
    EXIT_CODE=$(< "$TMP_EXIT_CODE")
else
    echo "$NAME: Warning: TMP_EXIT_CODE file is empty: $TMP_EXIT_CODE" 1>&2
    EXIT_CODE=12 # exit 12
    echo "$NAME: Notice: EXIT_CODE set to: $EXIT_CODE" 1>&2
fi
exit "$EXIT_CODE"
